### PR TITLE
Add secret 3

### PR DESCRIPTION
**Pull request by so0k**
Using Terraform modules to create more secrets

### CODE REVIEW

**Comment by so0k** [comment]
atlantis plan production

**Comment by honestbee-atlantis** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

random_pet.random_string: Refreshing state... (ID: brieflycleanlynaturalcoyote)
random_pet.random_string: Refreshing state... (ID: sadlyconverselycompletetahr)
null_resource.default: Refreshing state... (ID: 2365175403493862875)
random_id.random_number: Refreshing state... (ID: AGh4xw)
random_id.random_number: Refreshing state... (ID: P4XgJg)
null_resource.default: Refreshing state... (ID: 3869461967029363512)
null_resource.default: Refreshing state... (ID: 8798172113476225114)
data.null_data_source.default: Refreshing state...
data.null_data_source.default: Refreshing state...
aws_route53_health_check.origin2: Refreshing state... (ID: 4b67ac9f-58e0-4ac6-92d6-c3a671b4103c)
aws_route53_health_check.origin1: Refreshing state... (ID: 3a187ded-97f9-40f8-b7d7-c62af1046e23)
data.aws_route53_zone.main: Refreshing state...
aws_s3_bucket.default: Refreshing state... (ID: honestbee-production-devops-sg-demo)
aws_route53_record.origin2: Refreshing state... (ID: ZNCSEA5FAW4K2_devops-sg-demo.honestbee.com_CNAME_origin2)
aws_route53_record.origin1: Refreshing state... (ID: ZNCSEA5FAW4K2_devops-sg-demo.honestbee.com_CNAME_origin1)
vault_generic_secret.secrets: Refreshing state... (ID: secret/production/devops-sg-demo)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

~ vault_generic_secret.secrets
      data_json:            "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$0fE7lkMqi7Nwxk039exTJOOStgIVjEbJIeW.0b.9iAyG9ONhteGgS\",\"SECRET_HASH\":\"$2a$05$0iMfZVVcWowOpk3HB9ctZepElVHvgWHDz17bwpL5H/WDN8QdGKMWm\"}" => "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$K21im3szFjSyOZIXx2eWwurZi5IGmmyoxZrh2oyLTE7KLOOsa9foK\",\"SECRET3_HASH\":\"$2a$05$K21im3szFjSyOZIXx2eWwurZi5IGmmyoxZrh2oyLTE7KLOOsa9foK\",\"SECRET_HASH\":\"$2a$05$LpBwx87gpe5QhbYVE/btnO3WjbwL4obeVknFRRFQbzRZ11nHF2YtC\"}"

 <= module.secret3.data.null_data_source.default
      id:                   <computed>
      has_computed_default: <computed>
      inputs.%:             <computed>
      outputs.%:            <computed>
      random:               <computed>

  + module.secret3.random_id.random_number
      id:                   <computed>
      b64:                  <computed>
      b64_std:              <computed>
      b64_url:              <computed>
      byte_length:          "4"
      dec:                  <computed>
      hex:                  <computed>

  + module.secret3.random_pet.random_string
      id:                   <computed>
      length:               "4"
Plan: 2 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/devops-singapore-example/3/production/terraform/production.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/devops-singapore-example/3/production/terraform/production.tfplan"


```

* To **discard** this plan click [here](https://atlantis.internal.honestbee.com/lock?id=honestbee%252Fdevops-singapore-example%252Fterraform%252Fproduction).

**Comment by so0k** [comment]
atlantis apply production

**Comment by honestbee-atlantis** [comment]
```diff
module.secret3.random_pet.random_string: Creating...
  length: "" => "4"
module.secret3.random_id.random_number: Creating...
  b64:         "" => "<computed>"
  b64_std:     "" => "<computed>"
  b64_url:     "" => "<computed>"
  byte_length: "" => "4"
  dec:         "" => "<computed>"
  hex:         "" => "<computed>"
module.secret3.random_pet.random_string: Creation complete after 0s (ID: merelyneatlyworthygoshawk)
module.secret3.random_id.random_number: Creation complete after 0s (ID: xU6Fkw)
module.secret3.data.null_data_source.default: Refreshing state...
vault_generic_secret.secrets: Modifying... (ID: secret/production/devops-sg-demo)
  data_json: "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$0fE7lkMqi7Nwxk039exTJOOStgIVjEbJIeW.0b.9iAyG9ONhteGgS\",\"SECRET_HASH\":\"$2a$05$0iMfZVVcWowOpk3HB9ctZepElVHvgWHDz17bwpL5H/WDN8QdGKMWm\"}" => "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$K21im3szFjSyOZIXx2eWwurZi5IGmmyoxZrh2oyLTE7KLOOsa9foK\",\"SECRET3_HASH\":\"$2a$05$K21im3szFjSyOZIXx2eWwurZi5IGmmyoxZrh2oyLTE7KLOOsa9foK\",\"SECRET_HASH\":\"$2a$05$LpBwx87gpe5QhbYVE/btnO3WjbwL4obeVknFRRFQbzRZ11nHF2YtC\"}"
vault_generic_secret.secrets: Modifications complete after 0s (ID: secret/production/devops-sg-demo)

Apply complete! Resources: 2 added, 1 changed, 0 destroyed.

```

**Comment by honestbee-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `honestbee/devops-singapore-example/terraform` workspace: `production`

**Pull request merged**
