### PR TITLE
Add secret2

### PR DESCRIPTION
**Pull request by so0k**
Adding a second secret to the environment

(not saying secrets should be in environment, this is just a demo)

### CODE REVIEW

**Comment by so0k** [comment]
atlantis plan

**Comment by honestbee-atlantis** [comment]
**Plan Error**
```
exit status 1: running "sh -c terraform plan -refresh -no-color -out /root/.atlantis/repos/honestbee/devops-singapore-example/1/default/terraform/default.tfplan -var atlantis_user=so0k" in "/root/.atlantis/repos/honestbee/devops-singapore-example/1/default/terraform": 
provider.vault.address
  URL of the root of the target Vault server.

  Enter a value: 
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.main: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.vault: failed to create limited child token: Post /v1/auth/token/create: unsupported protocol scheme ""



provider.vault.address
  URL of the root of the target Vault server.

  Enter a value: 
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.main: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.vault: failed to create limited child token: Post /v1/auth/token/create: unsupported protocol scheme ""



```

**Comment by so0k** [comment]
atlantis plan

**Comment by honestbee-atlantis** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.main: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

+ vault_generic_secret.secrets
      id:                               <computed>
      data_json:                        <computed>
      disable_read:                     "false"
      path:                             "secret/default/devops-sg-demo"

  + module.s3bucket.aws_s3_bucket.default
      id:                               <computed>
      acceleration_status:              <computed>
      acl:                              "private"
      arn:                              <computed>
      bucket:                           "honestbee-default-devops-sg-demo"
      bucket_domain_name:               <computed>
      force_destroy:                    "true"
      hosted_zone_id:                   <computed>
      region:                           <computed>
      request_payer:                    <computed>
      tags.%:                           "3"
      tags.Name:                        "honestbee-default-devops-sg-demo"
      tags.Namespace:                   "honestbee"
      tags.Stage:                       "default"
      versioning.#:                     <computed>
      website_domain:                   <computed>
      website_endpoint:                 <computed>

 <= module.secret.data.null_data_source.default
      id:                               <computed>
      has_computed_default:             <computed>
      inputs.%:                         <computed>
      outputs.%:                        <computed>
      random:                           <computed>

  + module.secret.random_id.random_number
      id:                               <computed>
      b64:                              <computed>
      b64_std:                          <computed>
      b64_url:                          <computed>
      byte_length:                      "4"
      dec:                              <computed>
      hex:                              <computed>

  + module.secret.random_pet.random_string
      id:                               <computed>
      length:                           "4"

 <= module.secret2.data.null_data_source.default
      id:                               <computed>
      has_computed_default:             <computed>
      inputs.%:                         <computed>
      outputs.%:                        <computed>
      random:                           <computed>

  + module.secret2.random_id.random_number
      id:                               <computed>
      b64:                              <computed>
      b64_std:                          <computed>
      b64_url:                          <computed>
      byte_length:                      "4"
      dec:                              <computed>
      hex:                              <computed>

  + module.secret2.random_pet.random_string
      id:                               <computed>
      length:                           "4"

  + module.weighted_routes.aws_route53_health_check.origin1
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1a-devops-sg-demo-default.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-default-devops-sg-demo-origin1"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin1"
      tags.Stage:                       "default"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_health_check.origin2
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1b-devops-sg-demo-default.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-default-devops-sg-demo-origin2"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin2"
      tags.Stage:                       "default"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_record.origin1
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin1.id}"
      name:                             "devops-sg-demo-default.honestbee.com"
      records.#:                        "1"
      records.4061534672:               "apse1a-devops-sg-demo-default.honestbee.com"
      set_identifier:                   "origin1"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.weighted_routes.aws_route53_record.origin2
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin2.id}"
      name:                             "devops-sg-demo-default.honestbee.com"
      records.#:                        "1"
      records.3221100983:               "apse1b-devops-sg-demo-default.honestbee.com"
      set_identifier:                   "origin2"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.s3bucket.module.label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              ""
      triggers.id:                      "honestbee-default-devops-sg-demo"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "honestbee"
      triggers.short_id:                "ho-def-dev"
      triggers.stage:                   "default"

  + module.weighted_routes.module.origin1-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin1"
      triggers.id:                      "hb-default-devops-sg-demo-origin1"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-def-dev"
      triggers.stage:                   "default"

  + module.weighted_routes.module.origin2-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin2"
      triggers.id:                      "hb-default-devops-sg-demo-origin2"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-def-dev"
      triggers.stage:                   "default"
Plan: 13 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/devops-singapore-example/1/default/terraform/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/devops-singapore-example/1/default/terraform/default.tfplan"


```

* To **discard** this plan click [here](https://atlantis.internal.honestbee.com/lock?id=honestbee%252Fdevops-singapore-example%252Fterraform%252Fdefault).

**Comment by so0k** [comment]
atlantis plan production

**Comment by honestbee-atlantis** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.main: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

+ vault_generic_secret.secrets
      id:                               <computed>
      data_json:                        <computed>
      disable_read:                     "false"
      path:                             "secret/production/devops-sg-demo"

  + module.s3bucket.aws_s3_bucket.default
      id:                               <computed>
      acceleration_status:              <computed>
      acl:                              "private"
      arn:                              <computed>
      bucket:                           "honestbee-production-devops-sg-demo"
      bucket_domain_name:               <computed>
      force_destroy:                    "true"
      hosted_zone_id:                   <computed>
      region:                           <computed>
      request_payer:                    <computed>
      tags.%:                           "3"
      tags.Name:                        "honestbee-production-devops-sg-demo"
      tags.Namespace:                   "honestbee"
      tags.Stage:                       "production"
      versioning.#:                     <computed>
      website_domain:                   <computed>
      website_endpoint:                 <computed>

 <= module.secret.data.null_data_source.default
      id:                               <computed>
      has_computed_default:             <computed>
      inputs.%:                         <computed>
      outputs.%:                        <computed>
      random:                           <computed>

  + module.secret.random_id.random_number
      id:                               <computed>
      b64:                              <computed>
      b64_std:                          <computed>
      b64_url:                          <computed>
      byte_length:                      "4"
      dec:                              <computed>
      hex:                              <computed>

  + module.secret.random_pet.random_string
      id:                               <computed>
      length:                           "4"

 <= module.secret2.data.null_data_source.default
      id:                               <computed>
      has_computed_default:             <computed>
      inputs.%:                         <computed>
      outputs.%:                        <computed>
      random:                           <computed>

  + module.secret2.random_id.random_number
      id:                               <computed>
      b64:                              <computed>
      b64_std:                          <computed>
      b64_url:                          <computed>
      byte_length:                      "4"
      dec:                              <computed>
      hex:                              <computed>

  + module.secret2.random_pet.random_string
      id:                               <computed>
      length:                           "4"

  + module.weighted_routes.aws_route53_health_check.origin1
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1a-devops-sg-demo.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-production-devops-sg-demo-origin1"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin1"
      tags.Stage:                       "production"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_health_check.origin2
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1b-devops-sg-demo.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-production-devops-sg-demo-origin2"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin2"
      tags.Stage:                       "production"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_record.origin1
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin1.id}"
      name:                             "devops-sg-demo.honestbee.com"
      records.#:                        "1"
      records.3664008632:               "apse1a-devops-sg-demo.honestbee.com"
      set_identifier:                   "origin1"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.weighted_routes.aws_route53_record.origin2
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin2.id}"
      name:                             "devops-sg-demo.honestbee.com"
      records.#:                        "1"
      records.2663739552:               "apse1b-devops-sg-demo.honestbee.com"
      set_identifier:                   "origin2"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.s3bucket.module.label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              ""
      triggers.id:                      "honestbee-production-devops-sg-demo"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "honestbee"
      triggers.short_id:                "ho-pro-dev"
      triggers.stage:                   "production"

  + module.weighted_routes.module.origin1-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin1"
      triggers.id:                      "hb-production-devops-sg-demo-origin1"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-pro-dev"
      triggers.stage:                   "production"

  + module.weighted_routes.module.origin2-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin2"
      triggers.id:                      "hb-production-devops-sg-demo-origin2"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-pro-dev"
      triggers.stage:                   "production"
Plan: 13 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/devops-singapore-example/1/production/terraform/production.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/devops-singapore-example/1/production/terraform/production.tfplan"


```

* To **discard** this plan click [here](https://atlantis.internal.honestbee.com/lock?id=honestbee%252Fdevops-singapore-example%252Fterraform%252Fproduction).

**Comment by so0k** [comment]
atlantis plan production

**Comment by honestbee-atlantis** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

random_pet.random_string: Refreshing state... (ID: brieflycleanlynaturalcoyote)
random_id.random_number: Refreshing state... (ID: AGh4xw)
null_resource.default: Refreshing state... (ID: 2259244135961502385)
null_resource.default: Refreshing state... (ID: 5533865737874474429)
null_resource.default: Refreshing state... (ID: 8798172113476225114)
data.null_data_source.default: Refreshing state...
aws_route53_health_check.origin2: Refreshing state... (ID: f0736da3-9ba3-480e-91ec-09eba5412d56)
aws_route53_health_check.origin1: Refreshing state... (ID: 34bcb3cf-bd96-4bb9-adcb-ba34922a4cef)
data.aws_route53_zone.main: Refreshing state...
aws_s3_bucket.default: Refreshing state... (ID: honestbee-production-devops-sg-demo)
aws_route53_record.origin2: Refreshing state... (ID: ZNCSEA5FAW4K2_devops-sg-demo.honestbee.com_CNAME_origin2)
aws_route53_record.origin1: Refreshing state... (ID: ZNCSEA5FAW4K2_devops-sg-demo.honestbee.com_CNAME_origin1)
vault_generic_secret.secrets: Refreshing state... (ID: secret/production/devops-sg-demo)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

~ vault_generic_secret.secrets
      data_json:            "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET_HASH\":\"$2a$05$AXfBpwUnalzjHudcv/hk1u4QzMjGRveSp/ch2neLI3/80.SPqSeQG\"}" => <computed>

 <= module.secret2.data.null_data_source.default
      id:                   <computed>
      has_computed_default: <computed>
      inputs.%:             <computed>
      outputs.%:            <computed>
      random:               <computed>

  + module.secret2.random_id.random_number
      id:                   <computed>
      b64:                  <computed>
      b64_std:              <computed>
      b64_url:              <computed>
      byte_length:          "4"
      dec:                  <computed>
      hex:                  <computed>

  + module.secret2.random_pet.random_string
      id:                   <computed>
      length:               "4"
Plan: 2 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/devops-singapore-example/1/production/terraform/production.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/devops-singapore-example/1/production/terraform/production.tfplan"


```

* To **discard** this plan click [here](https://atlantis.internal.honestbee.com/lock?id=honestbee%252Fdevops-singapore-example%252Fterraform%252Fproduction).

**Comment by so0k** [comment]
atlantis apply production

**Comment by honestbee-atlantis** [comment]
**Apply Failed**: Pull request must be approved before running apply.

**Comment by so0k** [comment]
atlantis apply production

**Comment by honestbee-atlantis** [comment]
**Apply Failed**: Pull request must be approved before running apply.

**Comment by honestbee-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `honestbee/devops-singapore-example/terraform` workspaces: `default`, `production`

**Pull request merged**
