### PR TITLE
Add weighted routes

### PR DESCRIPTION
**Pull request by so0k**
Add weighted route53 records and health checks

### CODE REVIEW

**Comment by so0k** [comment]
atlantis plan

**Comment by honestbee-atlantis** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.main: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

+ vault_generic_secret.secrets
      id:                               <computed>
      data_json:                        <computed>
      disable_read:                     "false"
      path:                             "secret/default/devops-sg-demo"

  + module.s3bucket.aws_s3_bucket.default
      id:                               <computed>
      acceleration_status:              <computed>
      acl:                              "private"
      arn:                              <computed>
      bucket:                           "honestbee-default-devops-sg-demo"
      bucket_domain_name:               <computed>
      force_destroy:                    "true"
      hosted_zone_id:                   <computed>
      region:                           <computed>
      request_payer:                    <computed>
      tags.%:                           "3"
      tags.Name:                        "honestbee-default-devops-sg-demo"
      tags.Namespace:                   "honestbee"
      tags.Stage:                       "default"
      versioning.#:                     <computed>
      website_domain:                   <computed>
      website_endpoint:                 <computed>

 <= module.secret.data.null_data_source.default
      id:                               <computed>
      has_computed_default:             <computed>
      inputs.%:                         <computed>
      outputs.%:                        <computed>
      random:                           <computed>

  + module.secret.random_id.random_number
      id:                               <computed>
      b64:                              <computed>
      b64_std:                          <computed>
      b64_url:                          <computed>
      byte_length:                      "4"
      dec:                              <computed>
      hex:                              <computed>

  + module.secret.random_pet.random_string
      id:                               <computed>
      length:                           "4"

 <= module.secret2.data.null_data_source.default
      id:                               <computed>
      has_computed_default:             <computed>
      inputs.%:                         <computed>
      outputs.%:                        <computed>
      random:                           <computed>

  + module.secret2.random_id.random_number
      id:                               <computed>
      b64:                              <computed>
      b64_std:                          <computed>
      b64_url:                          <computed>
      byte_length:                      "4"
      dec:                              <computed>
      hex:                              <computed>

  + module.secret2.random_pet.random_string
      id:                               <computed>
      length:                           "4"

  + module.weighted_routes.aws_route53_health_check.origin1
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1a-devops-sg-demo-default.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-default-devops-sg-demo-origin1"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin1"
      tags.Stage:                       "default"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_health_check.origin2
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1b-devops-sg-demo-default.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-default-devops-sg-demo-origin2"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin2"
      tags.Stage:                       "default"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_record.origin1
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin1.id}"
      name:                             "devops-sg-demo-default.honestbee.com"
      records.#:                        "1"
      records.4061534672:               "apse1a-devops-sg-demo-default.honestbee.com"
      set_identifier:                   "origin1"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.weighted_routes.aws_route53_record.origin2
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin2.id}"
      name:                             "devops-sg-demo-default.honestbee.com"
      records.#:                        "1"
      records.3221100983:               "apse1b-devops-sg-demo-default.honestbee.com"
      set_identifier:                   "origin2"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.s3bucket.module.label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              ""
      triggers.id:                      "honestbee-default-devops-sg-demo"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "honestbee"
      triggers.short_id:                "ho-def-dev"
      triggers.stage:                   "default"

  + module.weighted_routes.module.origin1-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin1"
      triggers.id:                      "hb-default-devops-sg-demo-origin1"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-def-dev"
      triggers.stage:                   "default"

  + module.weighted_routes.module.origin2-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin2"
      triggers.id:                      "hb-default-devops-sg-demo-origin2"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-def-dev"
      triggers.stage:                   "default"
Plan: 13 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/devops-singapore-example/4/default/terraform/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/devops-singapore-example/4/default/terraform/default.tfplan"


```

* To **discard** this plan click [here](https://atlantis.internal.honestbee.com/lock?id=honestbee%252Fdevops-singapore-example%252Fterraform%252Fdefault).

**Comment by so0k** [comment]
atlantis plan production

**Comment by honestbee-atlantis** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

random_id.random_number: Refreshing state... (ID: AGh4xw)
random_pet.random_string: Refreshing state... (ID: brieflycleanlynaturalcoyote)
random_pet.random_string: Refreshing state... (ID: sadlyconverselycompletetahr)
random_id.random_number: Refreshing state... (ID: P4XgJg)
null_resource.default: Refreshing state... (ID: 8798172113476225114)
data.null_data_source.default: Refreshing state...
data.null_data_source.default: Refreshing state...
data.aws_route53_zone.main: Refreshing state...
aws_s3_bucket.default: Refreshing state... (ID: honestbee-production-devops-sg-demo)
vault_generic_secret.secrets: Refreshing state... (ID: secret/production/devops-sg-demo)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

~ vault_generic_secret.secrets
      data_json:                        "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$y1eBmuoKOcEW7YfgMBiL6epH4/SHLSM1b/miPVbfhdY.sk05CuMiW\",\"SECRET_HASH\":\"$2a$05$nfEgAxK6X/9VAn.F.eucRe5cZ/qs6C9pUovvi4JU2weFUpBlDn5Z.\"}" => "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$0fE7lkMqi7Nwxk039exTJOOStgIVjEbJIeW.0b.9iAyG9ONhteGgS\",\"SECRET_HASH\":\"$2a$05$0iMfZVVcWowOpk3HB9ctZepElVHvgWHDz17bwpL5H/WDN8QdGKMWm\"}"

  + module.weighted_routes.aws_route53_health_check.origin1
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1a-devops-sg-demo.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-production-devops-sg-demo-origin1"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin1"
      tags.Stage:                       "production"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_health_check.origin2
      id:                               <computed>
      enable_sni:                       <computed>
      failure_threshold:                "5"
      fqdn:                             "apse1b-devops-sg-demo.honestbee.com"
      measure_latency:                  "false"
      port:                             "80"
      request_interval:                 "30"
      resource_path:                    "/"
      tags.%:                           "4"
      tags.Name:                        "hb-production-devops-sg-demo-origin2"
      tags.Namespace:                   "hb"
      tags.Origin:                      "origin2"
      tags.Stage:                       "production"
      type:                             "HTTP"

  + module.weighted_routes.aws_route53_record.origin1
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin1.id}"
      name:                             "devops-sg-demo.honestbee.com"
      records.#:                        "1"
      records.3664008632:               "apse1a-devops-sg-demo.honestbee.com"
      set_identifier:                   "origin1"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.weighted_routes.aws_route53_record.origin2
      id:                               <computed>
      allow_overwrite:                  "true"
      fqdn:                             <computed>
      health_check_id:                  "${aws_route53_health_check.origin2.id}"
      name:                             "devops-sg-demo.honestbee.com"
      records.#:                        "1"
      records.2663739552:               "apse1b-devops-sg-demo.honestbee.com"
      set_identifier:                   "origin2"
      ttl:                              "120"
      type:                             "CNAME"
      weighted_routing_policy.#:        "1"
      weighted_routing_policy.0.weight: "50"
      zone_id:                          "ZNCSEA5FAW4K2"

  + module.weighted_routes.module.origin1-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin1"
      triggers.id:                      "hb-production-devops-sg-demo-origin1"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-pro-dev"
      triggers.stage:                   "production"

  + module.weighted_routes.module.origin2-label.null_resource.default
      id:                               <computed>
      triggers.%:                       "6"
      triggers.attributes:              "origin2"
      triggers.id:                      "hb-production-devops-sg-demo-origin2"
      triggers.name:                    "devops-sg-demo"
      triggers.namespace:               "hb"
      triggers.short_id:                "hb-pro-dev"
      triggers.stage:                   "production"
Plan: 6 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/devops-singapore-example/4/production/terraform/production.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/devops-singapore-example/4/production/terraform/production.tfplan"


```

* To **discard** this plan click [here](https://atlantis.internal.honestbee.com/lock?id=honestbee%252Fdevops-singapore-example%252Fterraform%252Fproduction).

**Comment by so0k** [comment]
atlantis apply production

**Comment by honestbee-atlantis** [comment]
```diff
module.weighted_routes.module.origin2-label.null_resource.default: Creating...
  triggers.%:          "" => "6"
  triggers.attributes: "" => "origin2"
  triggers.id:         "" => "hb-production-devops-sg-demo-origin2"
  triggers.name:       "" => "devops-sg-demo"
  triggers.namespace:  "" => "hb"
  triggers.short_id:   "" => "hb-pro-dev"
  triggers.stage:      "" => "production"
module.weighted_routes.module.origin1-label.null_resource.default: Creating...
  triggers.%:          "" => "6"
  triggers.attributes: "" => "origin1"
  triggers.id:         "" => "hb-production-devops-sg-demo-origin1"
  triggers.name:       "" => "devops-sg-demo"
  triggers.namespace:  "" => "hb"
  triggers.short_id:   "" => "hb-pro-dev"
  triggers.stage:      "" => "production"
module.weighted_routes.module.origin2-label.null_resource.default: Creation complete after 0s (ID: 2365175403493862875)
module.weighted_routes.module.origin1-label.null_resource.default: Creation complete after 0s (ID: 3869461967029363512)
vault_generic_secret.secrets: Modifying... (ID: secret/production/devops-sg-demo)
  data_json: "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$y1eBmuoKOcEW7YfgMBiL6epH4/SHLSM1b/miPVbfhdY.sk05CuMiW\",\"SECRET_HASH\":\"$2a$05$nfEgAxK6X/9VAn.F.eucRe5cZ/qs6C9pUovvi4JU2weFUpBlDn5Z.\"}" => "{\"AWS_REGION\":\"ap-southeast-1\",\"AWS_S3_BUCKET\":\"honestbee-production-devops-sg-demo\",\"HOST\":\"devops-sg-demo.honestbee.com\",\"SECRET2_HASH\":\"$2a$05$0fE7lkMqi7Nwxk039exTJOOStgIVjEbJIeW.0b.9iAyG9ONhteGgS\",\"SECRET_HASH\":\"$2a$05$0iMfZVVcWowOpk3HB9ctZepElVHvgWHDz17bwpL5H/WDN8QdGKMWm\"}"
vault_generic_secret.secrets: Modifications complete after 0s (ID: secret/production/devops-sg-demo)
module.weighted_routes.aws_route53_health_check.origin2: Creating...
  enable_sni:        "" => "<computed>"
  failure_threshold: "" => "5"
  fqdn:              "" => "apse1b-devops-sg-demo.honestbee.com"
  measure_latency:   "" => "false"
  port:              "" => "80"
  request_interval:  "" => "30"
  resource_path:     "" => "/"
  tags.%:            "" => "4"
  tags.Name:         "" => "hb-production-devops-sg-demo-origin2"
  tags.Namespace:    "" => "hb"
  tags.Origin:       "" => "origin2"
  tags.Stage:        "" => "production"
  type:              "" => "HTTP"
module.weighted_routes.aws_route53_health_check.origin1: Creating...
  enable_sni:        "" => "<computed>"
  failure_threshold: "" => "5"
  fqdn:              "" => "apse1a-devops-sg-demo.honestbee.com"
  measure_latency:   "" => "false"
  port:              "" => "80"
  request_interval:  "" => "30"
  resource_path:     "" => "/"
  tags.%:            "" => "4"
  tags.Name:         "" => "hb-production-devops-sg-demo-origin1"
  tags.Namespace:    "" => "hb"
  tags.Origin:       "" => "origin1"
  tags.Stage:        "" => "production"
  type:              "" => "HTTP"
module.weighted_routes.aws_route53_health_check.origin2: Creation complete after 4s (ID: 4b67ac9f-58e0-4ac6-92d6-c3a671b4103c)
module.weighted_routes.aws_route53_health_check.origin1: Creation complete after 4s (ID: 3a187ded-97f9-40f8-b7d7-c62af1046e23)
module.weighted_routes.aws_route53_record.origin2: Creating...
  allow_overwrite:                  "" => "true"
  fqdn:                             "" => "<computed>"
  health_check_id:                  "" => "4b67ac9f-58e0-4ac6-92d6-c3a671b4103c"
  name:                             "" => "devops-sg-demo.honestbee.com"
  records.#:                        "" => "1"
  records.2663739552:               "" => "apse1b-devops-sg-demo.honestbee.com"
  set_identifier:                   "" => "origin2"
  ttl:                              "" => "120"
  type:                             "" => "CNAME"
  weighted_routing_policy.#:        "" => "1"
  weighted_routing_policy.0.weight: "" => "50"
  zone_id:                          "" => "ZNCSEA5FAW4K2"
module.weighted_routes.aws_route53_record.origin1: Creating...
  allow_overwrite:                  "" => "true"
  fqdn:                             "" => "<computed>"
  health_check_id:                  "" => "3a187ded-97f9-40f8-b7d7-c62af1046e23"
  name:                             "" => "devops-sg-demo.honestbee.com"
  records.#:                        "" => "1"
  records.3664008632:               "" => "apse1a-devops-sg-demo.honestbee.com"
  set_identifier:                   "" => "origin1"
  ttl:                              "" => "120"
  type:                             "" => "CNAME"
  weighted_routing_policy.#:        "" => "1"
  weighted_routing_policy.0.weight: "" => "50"
  zone_id:                          "" => "ZNCSEA5FAW4K2"
module.weighted_routes.aws_route53_record.origin2: Still creating... (10s elapsed)
module.weighted_routes.aws_route53_record.origin1: Still creating... (10s elapsed)
module.weighted_routes.aws_route53_record.origin2: Still creating... (20s elapsed)
module.weighted_routes.aws_route53_record.origin1: Still creating... (20s elapsed)
module.weighted_routes.aws_route53_record.origin2: Still creating... (30s elapsed)
module.weighted_routes.aws_route53_record.origin1: Still creating... (30s elapsed)
module.weighted_routes.aws_route53_record.origin2: Still creating... (40s elapsed)
module.weighted_routes.aws_route53_record.origin1: Still creating... (40s elapsed)
module.weighted_routes.aws_route53_record.origin2: Still creating... (50s elapsed)
module.weighted_routes.aws_route53_record.origin1: Still creating... (50s elapsed)
module.weighted_routes.aws_route53_record.origin2: Creation complete after 53s (ID: ZNCSEA5FAW4K2_devops-sg-demo.honestbee.com_CNAME_origin2)
module.weighted_routes.aws_route53_record.origin1: Creation complete after 53s (ID: ZNCSEA5FAW4K2_devops-sg-demo.honestbee.com_CNAME_origin1)

Apply complete! Resources: 6 added, 1 changed, 0 destroyed.

```

**Comment by honestbee-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `honestbee/devops-singapore-example/terraform` workspaces: `default`, `production`

**Pull request merged**
